In [1]:
import numpy as np

### 1. Linear Regression

In [4]:
class CustomLinearRegression:
    def __init__(self, X_data, y_target, learning_rate=0.01, num_epochs=10000):
        self.num_samples = X_data.shape[0]
        self.X_data = np.c_[np.ones((self.num_samples, 1)), X_data]  # Add bias term
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs

        # Initialize weights randomly
        self.theta = np.random.randn(self.X_data.shape[1], 1)
        self.losses = []

    def compute_loss(self, y_pred, y_target):
        error = y_pred - y_target   
        loss = (1 / (2 * self.num_samples)) * np.sum(error ** 2)  #
        return loss

    def predict(self, X_data):
        X_data = np.c_[np.ones((X_data.shape[0], 1)), X_data]
        y_pred = X_data.dot(self.theta)
        return y_pred

    def fit(self):
        for epoch in range(self.num_epochs):
            # Make predictions 
            y_pred = self.predict(self.X_data)

            # Compute the loss
            loss = self.compute_loss(y_pred, self.y_target)
            self.losses.append(loss)

            # Gradient descent step
            loss_gradients = 2 * (y_pred - self.y_target) / self.num_samples
            gradient = self.X_data.T.dot(loss_gradients)

            # Update weights using gradient descent
            self.theta -= self.learning_rate * gradient

            # Print loss every 50 epochs
            if (epoch % 50) == 0:
                print(f'Epoch: {epoch} - Loss: {loss}')

        return {
            'loss': sum(self.losses) / len(self.losses),
            'weight': self.theta
        }
    

In [5]:
def r2score(y_pred, y):
   rss = np.sum((y - y_pred) ** 2)
   tss = np.sum((y - np.mean(y)) ** 2)
   r2 = 1 - (rss / tss)
   return r2

In [7]:
#  Câu 4.1
y_pred = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])
r2score(y_pred, y)


1.0

In [8]:
#  Câu 4.2
y_pred = np.array([1, 2, 3, 4, 5])
y = np.array([3, 5, 5, 2, 4])
r2score(y_pred, y)

-2.235294117647059

### 2. Polynomial Regression

In [22]:
def create_polynomial_features(X, degree=2):
   X_new = X
   for i in range(2, degree + 1):
      X_new = np.c_[X_new, np.power(X, i)]
   return X_new

X = np.array([[1], [2], [3]])
X_poly = create_polynomial_features(X, degree=2)
print(X_poly)

[[1 1]
 [2 4]
 [3 9]]


In [26]:
def create_polynomial_features(X, degree=2):
    X_mem = []
    for X_sub in X.T:
        X_sub = X_sub.T
        X_new = X_sub
        for d in range(2, degree + 1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T


X = np.array([[1, 2], [2, 3], [3, 4]])
X_poly = create_polynomial_features(X, degree=2)
print(X_poly)


[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]


### 3. Sales Prediction

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('data/SalesPrediction.csv')
df

TV      Radio  Social Media Influencer       Sales
0     16.0   6.566231      2.907983       Mega   54.732757
1     13.0   9.237765      2.409567       Mega   46.677897
2     41.0  15.886446      2.913410       Mega  150.177829
3     83.0  30.020028      6.922304       Mega  298.246340
4     15.0   8.437408      1.405998      Micro   56.594181
...    ...        ...           ...        ...         ...
4567  26.0   4.472360      0.717090      Micro   94.685866
4568  71.0  20.610685      6.545573       Nano  249.101915
4569  44.0  19.800072      5.096192      Micro  163.631457
4570  71.0  17.534640      1.940873      Macro  253.610411
4571  42.0  15.966688      5.046548      Micro  148.202414

[4572 rows x 5 columns]

In [35]:
#  Chuyển thành OneHot-Encoding
df = pd.get_dummies(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   TV                4572 non-null   float64
 1   Radio             4572 non-null   float64
 2   Social Media      4572 non-null   float64
 3   Sales             4572 non-null   float64
 4   Influencer_Macro  4572 non-null   bool   
 5   Influencer_Mega   4572 non-null   bool   
 6   Influencer_Micro  4572 non-null   bool   
 7   Influencer_Nano   4572 non-null   bool   
dtypes: bool(4), float64(4)
memory usage: 160.9 KB


In [36]:
df = df.fillna(df.mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   TV                4572 non-null   float64
 1   Radio             4572 non-null   float64
 2   Social Media      4572 non-null   float64
 3   Sales             4572 non-null   float64
 4   Influencer_Macro  4572 non-null   bool   
 5   Influencer_Mega   4572 non-null   bool   
 6   Influencer_Micro  4572 non-null   bool   
 7   Influencer_Nano   4572 non-null   bool   
dtypes: bool(4), float64(4)
memory usage: 160.9 KB


In [ ]:
# Get features
X = df[['TV', 'Radio', 'Social Media', 'Influencer_Macro', 'Influencer_Mega', 'Influencer_Micro', 'Influencer_Nano']]
y = df[['Sales']]
